services:
  - type: web
    name: mqtt-influx-web
    runtime: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: MQTT_BROKER
        value: b56316a2eca748c3ac5d5113b291cb4c.s1.eu.hivemq.cloud
      - key: MQTT_PORT
        value: "8883"
      - key: MQTT_USERNAME
        value: admin
      - key: MQTT_PASSWORD
        value: Admin123
      - key: MQTT_TOPIC_FLUJO
        value: contador/01/flujo
      - key: MQTT_TOPIC_VOLUMEN
        value: contador/01/volumen
      - key: MQTT_TOPIC_VALVULA_APERTURA
        value: valvula/01/apertura
      - key: MQTT_TOPIC_CONSIGNA
        value: valvula/01/consigna
      - key: INFLUXDB_URL
        value: https://us-west-2-1.aws.cloud2.influxdata.com
      - key: INFLUXDB_TOKEN
        value: vGnSUXDrCJx-4lLQDS_GPkoESfjDPCvbBfPcMtFbTVwLMfYgG4vyDzmoJ0RxVTTzXhBNH4NxCkqM6BrYxgEujA==
      - key: INFLUXDB_ORG
        value: udc
      - key: INFLUXDB_BUCKET
        value: consumo_agua