services:
  - type: web
    name: mqtt-influx-service
    runtime: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - fromDotEnv: true
    autoDeploy: false
